### ISSUE TITLE
Missing feature: Blog cover in index.hbs

### ISSUE THREAD

**Issue by icaroperseo** [sandrokeil/ghost-theme-casperion#6]
Good day!

Testing your theme, I discovered that I was not able to correctly set the blog cover. To retrieve this feature is necessary to replace the following line:

```
--- Ghost/casperion/a/index.hbs
+++ Ghost/casperion/b/index.hbs
@@ -2,7 +2,7 @@
 {{! The tag above means - insert everything in this file into the {body} of the default.hbs template }}
 
 {{! The big featured header }}
-<header class="main-header cover">
+<header class="main-header {{#if @blog.cover}}" style="background-image: url({{@blog.cover}}){{else}}no-cover{{/if}}">
     <nav class="main-nav overlay clearfix">
         {{#if @blog.logo}}<a class="blog-logo" href="{{@blog.url}}" title="{{@blog.title}}"><img src="{{@blog.logo}}" alt="Blog Logo" /></a>{{/if}}
     </nav>
```

I hope you find it useful.

Best regards.

**Comment by sandrokeil** [comment]
Thank you very much @icaroperseo . Check out the new release 1.1.2.

**Comment by sagarmunjal** [comment]
Hi, i would like to know from where does this templating engine pick the picture, {{#if @blog.cover }} where is the url "blog.cover" and how to set it to a picture of my choice??

**Comment by sandrokeil** [comment]
@sagarmunjal I guess you have to upload the blog cover image via the ghost backend (settings -> general).
